import { pgEnum, pgTable, serial, varchar, text, integer, timestamp, numeric, boolean, jsonb } from "drizzle-orm/pg-core";

export const queryStatusEnum = pgEnum("query_status", ["new", "contacted", "quoted", "converted", "closed"]);
export const sortOptionEnum = pgEnum("sort_option", ["newest", "price_asc", "price_desc", "name_asc"]);
export const stockStatusEnum = pgEnum("stock_status", ["in_stock", "out_of_stock", "pre_order"]);

export const brands = pgTable("brands", { id: serial("id").primaryKey(), name: varchar("name").notNull(), slug: varchar("slug").notNull(), logoUrl: text("logo_url"), createdAt: timestamp("created_at").defaultNow().notNull() });
export const categories = pgTable("categories", { id: serial("id").primaryKey(), name: varchar("name").notNull(), slug: varchar("slug").notNull(), createdAt: timestamp("created_at").defaultNow().notNull() });
export const products = pgTable("products", { id: serial("id").primaryKey(), name: varchar("name").notNull(), slug: varchar("slug").notNull(), description: text("description"), mrp: numeric("mrp").notNull(), images: jsonb("images").default([]).notNull(), categoryId: integer("category_id"), brandId: integer("brand_id"), moq: integer("moq").default(1).notNull(), stockStatus: stockStatusEnum("stock_status").default("in_stock").notNull(), tags: jsonb("tags").default([]).notNull(), isActive: boolean("is_active").default(true).notNull(), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull() });
export const catalogueLinks = pgTable("catalogue_links", { id: serial("id").primaryKey(), slug: varchar("slug").notNull(), customerName: varchar("customer_name"), companyName: varchar("company_name"), mobileNo: varchar("mobile_no"), email: varchar("email"), brandIds: jsonb("brand_ids").default([]).notNull(), categoryIds: jsonb("category_ids").default([]).notNull(), minPrice: numeric("min_price"), maxPrice: numeric("max_price"), isActive: boolean("is_active").default(true).notNull(), viewCount: integer("view_count").default(0).notNull(), createdAt: timestamp("created_at").defaultNow().notNull(), defaultSort: sortOptionEnum("default_sort").default("newest").notNull(), productIds: jsonb("product_ids").default([]).notNull() });
export const bulkQueries = pgTable("bulk_queries", { id: serial("id").primaryKey(), queryType: varchar("query_type").default("catalogue").notNull(), catalogueLinkId: integer("catalogue_link_id"), categoryId: integer("category_id").references(() => categories.id, { onDelete: "set null" }), categoryIds: jsonb("category_ids").default([]).notNull(), brandIds: jsonb("brand_ids").default([]).notNull(), quantity: integer("quantity"), name: varchar("name").notNull(), companyName: varchar("company_name"), contactNo: varchar("contact_no").notNull(), email: varchar("email"), preferredCallTime: varchar("preferred_call_time"), preferredCallAt: timestamp("preferred_call_at"), status: queryStatusEnum("status").default("new").notNull(), notes: text("notes"), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull() });
export const bulkQueryItems = pgTable("bulk_query_items", { id: serial("id").primaryKey(), bulkQueryId: integer("bulk_query_id").notNull(), productId: integer("product_id").notNull(), quantity: integer("quantity").default(1) });
export const images = pgTable("images", { id: serial("id").primaryKey(), url: text("url").notNull(), productId: integer("product_id"), brandId: integer("brand_id"), isPrimary: boolean("is_primary").default(false).notNull(), sortOrder: integer("sort_order").default(0).notNull(), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull() });
export const linkViews = pgTable("link_views", { id: serial("id").primaryKey(), catalogueLinkId: integer("catalogue_link_id"), viewedAt: timestamp("viewed_at").defaultNow().notNull() });
export const productClicks = pgTable("product_clicks", { id: serial("id").primaryKey(), catalogueLinkId: integer("catalogue_link_id"), productId: integer("product_id").notNull(), clickedAt: timestamp("clicked_at").defaultNow().notNull() });
export const settings = pgTable("settings", { id: serial("id").primaryKey(), brandName: varchar("brand_name").notNull(), brandDescription: text("brand_description"), brandTagline: varchar("brand_tagline"), brandLogo: text("brand_logo"), brandFavicon: text("brand_favicon"), contactNumber: varchar("contact_number"), alternateContactNumber: varchar("alternate_contact_number"), whatsappNumber: varchar("whatsapp_number"), email: varchar("email"), addressLine1: varchar("address_line1"), addressLine2: varchar("address_line2"), city: varchar("city"), state: varchar("state"), country: varchar("country").default("India"), pincode: varchar("pincode"), latitude: numeric("latitude"), longitude: numeric("longitude"), googleMapsUrl: text("google_maps_url"), website: text("website"), instagram: text("instagram"), facebook: text("facebook"), youtube: text("youtube"), linkedin: text("linkedin"), twitter: text("twitter"), gstNumber: varchar("gst_number") });
