export type Relationship = { table: string; label: string; secondary?: string };
export type Field = { name: string; label?: string; type?: "text" | "number" | "email" | "url" | "textarea" | "boolean" | "json" | "date" | "enum" | "reference" | "multi-reference" | "image" | "image-list"; required?: boolean; options?: string[]; editable?: boolean; relationship?: Relationship };
export type TableConfig = { label: string; description: string; fields: Field[]; allowCreate?: boolean; allowEdit?: boolean; allowDelete?: boolean };
const f = (name: string, type: Field["type"] = "text", required = false, options?: string[], relationship?: Relationship): Field => ({ name, type, required, options, relationship });

export const adminTables: Record<string, TableConfig> = {
  brands: { label: "Brands", description: "Manage the brands shown across your catalogue.", fields: [f("name", "text", true), f("slug"), f("logo_url", "image"), f("created_at", "date")] },
  categories: { label: "Categories", description: "Organize products into catalogue categories.", fields: [f("name", "text", true), f("slug"), f("created_at", "date")] },
  products: { label: "Products", description: "Manage pricing, availability, catalogue images and product details.", fields: [f("name", "text", true), f("slug"), f("description", "textarea"), f("mrp", "number", true), f("images", "image-list", true), f("category_id", "reference", false, undefined, { table: "categories", label: "name" }), f("brand_id", "reference", false, undefined, { table: "brands", label: "name" }), f("moq", "number", true), f("stock_status", "enum", true, ["in_stock", "out_of_stock", "pre_order"]), f("tags", "json"), f("is_active", "boolean", true), f("created_at", "date"), f("updated_at", "date")] },
  catalogue_links: { label: "Catalogue links", description: "Create and control shareable, targeted catalogues.", fields: [f("slug"), f("customer_name"), f("company_name"), f("mobile_no"), f("email", "email"), f("brand_ids", "multi-reference", false, undefined, { table: "brands", label: "name" }), f("category_ids", "multi-reference", false, undefined, { table: "categories", label: "name" }), f("min_price", "number"), f("max_price", "number"), f("is_active", "boolean", true), f("view_count", "number", true), f("created_at", "date"), f("default_sort", "enum", true, ["newest", "price_asc", "price_desc", "name_asc"]), f("product_ids", "multi-reference", false, undefined, { table: "products", label: "name" })] },
  bulk_queries: { label: "Requirements", description: "Review catalogue enquiries and general requirements from customers.", allowCreate: false, allowEdit: false, fields: [f("catalogue_link_id", "reference", false, undefined, { table: "catalogue_links", label: "slug" }), f("name", "text", true), f("company_name"), f("contact_no", "text", true), f("email", "email"), f("category_id", "reference", false, undefined, { table: "categories", label: "name" }), f("quantity", "number"), f("preferred_call_time"), f("status", "enum", true, ["new", "contacted", "quoted", "converted", "closed"]), f("notes", "textarea"), f("created_at", "date"), f("updated_at", "date")] },
  settings: { label: "Settings", description: "Manage storefront identity, contact details and social links.", fields: [f("brand_name", "text", true), f("brand_description", "textarea"), f("brand_tagline"), f("brand_logo", "image"), f("brand_favicon", "image"), f("contact_number"), f("alternate_contact_number"), f("whatsapp_number"), f("email", "email"), f("address_line1"), f("address_line2"), f("city"), f("state"), f("country"), f("pincode"), f("latitude", "number"), f("longitude", "number"), f("google_maps_url", "url"), f("website", "url"), f("instagram", "url"), f("facebook", "url"), f("youtube", "url"), f("linkedin", "url"), f("twitter", "url"), f("gst_number")] },
};
export const readOnlyFields = new Set(["id", "created_at", "updated_at", "viewed_at", "clicked_at"]);
export function getTable(name: string) { return Object.hasOwn(adminTables, name) ? adminTables[name] : undefined; }
